const ActionType = {
  REQ_GET_CURRICULUM: "REQ_GET_CURRICULUM",
  RES_GET_CURRICULUM: "RES_GET_CURRICULUM",

  REQ_GET_CURRICULUM_BY_ID: "REQ_GET_CURRICULUM_BY_ID",
  RES_GET_CURRICULUM_BY_ID: "RES_GET_CURRICULUM_BY_ID",

  REQ_CREATE_CURRICULUM: "REQ_CREATE_CURRICULUM",
  RES_CREATE_CURRICULUM: "RES_CREATE_CURRICULUM",

  REQ_UPDATE_CURRICULUM: "REQ_UPDATE_CURRICULUM",
  RES_UPDATE_CURRICULUM: "RES_UPDATE_CURRICULUM",

  REQ_GET_CURRNUM: "REQ_GET_CURRNUM",
  RES_GET_CURRNUM: "RES_GET_CURRNUM",

  RES_CREATE_SECTION: "RES_CREATE_SECTION",
  REQ_CREATE_SECTION: "REQ_CREATE_SECION",

  RES_CREATE_SECTION_DETAIL: "RES_CREATE_SECTION_DETAIL",
  REQ_CREATE_SECTION_DETAIL: "REQ_CREATE_SECION_DETAIL",

  RES_GET_MERGE: "RES_GET_MERGE",
  REQ_GET_MERGE: "REQ_GET_MERGE",

  REQ_EMPLOYEE: "REQ_EMPLOYEE",
  RES_EMPLOYEE: "RES_EMPLOYEE",
};

export default ActionType;
