const AuthActionTypes = {
    LOGIN: "LOGIN",
    LOGIN_RESPONSE: "LOGIN_RESPONSE",

    SIGNUPINTERNAL: "SIGNUPINTERNAL",
    SIGNUPINTERNAL_RESPONSE: "SIGNUPINTERNAL_RESPONSE",

    SIGNUPEXTERNAL: "SIGNUPEXTERNAL",
    SIGNUPEXTERNAL_RESPONSE: "SIGNUPEXTERNAL_RESPONSE",

    RESET_STATE: "RESET_STATE",
}

export default AuthActionTypes