const ActionType = {
  //Job Post
  REQ_GET_JOBPOST: "REQ_GET_JOBPOST",
  RES_GET_JOBPOST: "RES_GET_JOBPOST",

  REQ_GET_JOBPHOTO: "REQ_GET_JOBPHOTO",
  RES_GET_JOBPHOTO: "RES_GET_JOBPHOTO",

  REQ_GET_JOBPOST_BY_ID: "REQ_GET_JOBPOST_BY_ID",
  RES_GET_JOBPOST_BY_ID: "RES_GET_JOBPOST_BY_ID",

  REQ_GET_CURNUMBER: "REQ_GET_CURNUMBER",
  RES_GET_CURNUMBER: "RES_GET_CURNUMBER",

  REQ_ADD_JOBPOST: "REQ_ADD_JOBPOST",
  RES_ADD_JOBPOST: "RES_ADD_JOBPOST",

  REQ_UPDATE_JOBPOST: "REQ_UPDATE_JOBPOST",
  RES_UPDATE_JOBPOST: "RES_UPDATE_JOBPOST",

  REQ_DELETE_JOBPOST: "REQ_DELETE_JOBPOST",
  RES_DELETE_JOBPOST: "RES_DELETE_JOBPOST",

  REQ_UPDATE_STATUS: "REQ_UPDATE_STATUS",
  RES_UPDATE_STATUS: "RES_UPDATE_STATUS",

  REQ_SEARCH_JOBPOST: "REQ_SEARCH_JOBPOST",
  RES_SEARCH_JOBPOST: "RES_SEARCH_JOBPOST",

  //Client
  REQ_GET_CLIENT: "REQ_GET_CLIENT",
  RES_GET_CLIENT: "RES_GET_CLIENT",

  REQ_GET_CLIENT_BY_ID: "REQ_GET_CLIENT_BY_ID",
  RES_GET_CLIENT_BY_ID: "RES_GET_CLIENT_BY_ID",

  REQ_ADD_CLIENT: "REQ_ADD_CLIENT",
  RES_ADD_CLIENT: "RES_ADD_CLIENT",

  REQ_UPDATE_CLIENT: "REQ_UPDATE_CLIENT",
  RES_UPDATE_CLIENT: "RES_UPDATE_CLIENT",

  REQ_DELETE_CLIENT: "REQ_DELETE_CLIENT",
  RES_DELETE_CLIENT: "RES_DELETE_CLIENT",

  //Employee Range
  REQ_GET_EMPRANGE: "REQ_GET_EMPRANGE",
  RES_GET_EMPRANGE: "RES_GET_EMPRANGE",

  RESET_STATE: "RESET_STATE",

  //Talent Apply
  REQ_ADD_CANDIDATE_JOB: "REQ_ADD_CANDIDATE_JOB",
  RES_ADD_CANDIDATE_JOB: "RES_ADD_CANDIDATE_JOB",

  REQ_GET_CANDIDATE_APPLY_JOB: "REQ_GET_CANDIDATE_APPLY_JOB",
  RES_GET_CANDIDATE_APPLY_JOB: "RES_GET_CANDIDATE_APPLY_JOB",

  REQ_GET_CANDIDATE_INTERVIEW_JOB: "REQ_GET_CANDIDATE_INTERVIEW_JOB",
  RES_GET_CANDIDATE_INTERVIEW_JOB: "RES_GET_CANDIDATE_INTERVIEW_JOB",

  REQ_GET_CANDIDATE_CONTRACT_JOB: "REQ_GET_CANDIDATE_CONTRACT_JOB",
  RES_GET_CANDIDATE_CONTRACT_JOB: "RES_GET_CANDIDATE_CONTRACT_JOB",

  REQ_GET_CANDIDATE_FAILED_JOB: "REQ_GET_CANDIDATE_FAILED_JOB",
  RES_GET_CANDIDATE_FAILED_JOB: "RES_GET_CANDIDATE_FAILED_JOB",

  REQ_UPDATE_CANDIDATE_JOB: "REQ_UPDATE_CANDIDATE_JOB",
  RES_UPDATE_CANDIDATE_JOB: "RES_UPDATE_CANDIDATE_JOB",
};

export default ActionType;
