const ActionSalesTypes = {

    //cart item
    GET_CART_ITEM: 'GET_CART_ITEM',
    GET_CART_ITEM_RESPONSE: 'GET_CART_ITEM_RESPONSE',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    ADD_CART_ITEM_RESPONSE: 'ADD_CART_ITEM_RESPONSE',
    // UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
    // UPDATE_CART_ITEM_RESPONSE: 'UPDATE_CART_ITEM_RESPONSE',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
    DELETE_CART_ITEM_RESPONSE: 'DELETE_CART_ITEM_RESPONSE',

    //special offer
    GET_SPECIAL_OFFER: 'GET_SPECIAL_OFFER',
    GET_SPECIAL_OFFER_RESPONSE: 'GET_SPECIAL_OFFER_RESPONSE',
    ADD_SPECIAL_OFFER: 'ADD_SPECIAL_OFFER',
    ADD_SPECIAL_OFFER_RESPONSE: 'ADD_SPECIAL_OFFER_RESPONSE',
    // UPDATE_SPECIAL_OFFER: 'UPDATE_SPECIAL_OFFER',
    // UPDATE_SPECIAL_OFFER_RESPONSE: 'UPDATE_SPECIAL_OFFER_RESPONSE',
    DELETE_SPECIAL_OFFER: 'DELETE_SPECIAL_OFFER',
    DELETE_SPECIAL_OFFER_RESPONSE: 'DELETE_SPECIAL_OFFER_RESPONSE',

    GET_SALES_ORDER: 'GET_SALES_ORDER',
    GET_SALES_ORDER_RESPONSE: 'GET_SALES_ORDER_RESPONSE',
    ADD_SALES_ORDER: 'ADD_SALES_ORDER',
    ADD_SALES_ORDER_RESPONSE: 'ADD_SALES_ORDER_RESPONSE',
    // UPDATE_SALES_ORDER: 'UPDATE_SALES_ORDER',
    // UPDATE_SALES_ORDER_RESPONSE: 'UPDATE_SALES_ORDER_RESPONSE',
    DELETE_SALES_ORDER: 'DELETE_SALES_ORDER',
    DELETE_SALES_ORDER_RESPONSE: 'DELETE_SALES_ORDER_RESPONSE',

    GET_PAYMENT_REQUEST: 'GET_PAYMENT_REQUEST',
    GET_PAYMENT_RESPONSE: 'GET_PAYMENT_RESPONSE'
}

export default ActionSalesTypes