const ActionTypes = {
  // employee internall
  REQ_GET_EMPLOYEE: "REQ_GET_EMPLOYEE",
  RES_GET_EMPLOYEE: "RES_GET_EMPLOYEE",

  REQ_GET_FOR_EMPLOYEE: "REQ_GET_FOR_EMPLOYEE",
  RES_GET_FOR_EMPLOYEE: "RES_GET_FOR_EMPLOYEE",

  REQ_UPDATE: "REQ_UPDATE",
  RES_UPDATE: "RES_UPDATE",

  REQ_GET_FILTER_DEPARTMENT: "REQ_GET_FILTER_DEPARTMENT",
  RES_GET_FILTER_DEPARTMENT: "RES_GET_FILTER_DEPARTMENT",

  REQ_GET_FILTER_JOBROLE: "REQ_GET_FILTER_JOBROLE",
  RES_GET_FILTER_JOBROLE: "RES_GET_FILTER_JOBROLE",

  REQ_GET_FILTER_USERROLE: "REQ_GET_FILTER_USERROLE",
  RES_GET_FILTER_USERROLE: "RES_GET_FILTER_USERROLE",

  REQ_CREATE_EMPLOYE_INTERNAL: "REQ_CREATE_EMPLOYE_INTERNAL",
  RES_CREATE_EMPLOYE_INTERNAL: "RES_CREATE_EMPLOYE_INTERNAL",

  REQ_TALENT_JOB_POST: "REQ_TALENT_JOB_POST",
  RES_TALENT_JOB_POST: "RES_TALENT_JOB_POST",

  REQ_JOBTYPE: "REQ_JOBTYPE",
  RES_JOBTYPE: "RES_JOBTYPE",

  REQ_TALENT: "REQ_TALENT",
  RES_TALENT: "RES_TALENT",

  REQ_CLIENT_BOOTCAMP: "REQ_CLIENT_BOOTCAMP",
  RES_CLIENT_BOOTCAMP: "RES_CLIENT_BOOTCAMP",

  REQ_CREATE_BOOTCAMP: "REQ_CREATE_BOOTCAMP",
  RES_CREATE_BOOTCAMP: "RES_CREATE_BOOTCAMP",

  REQ_FIND_EMPLOYEE: "REQ_FIND_EMPLOYEE",
  RES_FIND_EMPLOYEE: "RES_FIND_EMPLOYEE",

  REQ_DEPARTMENT_HISTORY: "REQ_DEPARTMENT_HISTORY",
  RES_DEPARTMENT_HISTORY: "RES_DEPARTMENT_HISTORY",

  REQ_PAY_HISTORY: "REQ_PAY_HISTORY",
  RES_PAY_HISTORY: "RES_PAY_HISTORY",

  RESET_STATE: "RESET_STATE",
};

export default ActionTypes;
