const ActionType = {
    REQ_GET_BOOTCAMP : 'REQ_GET_BOOTCAMP',
    RES_GET_BOOTCAMP : 'RES_GET_BOOTCAMP',
    REQ_CREATE_BOOTCAMP : 'REQ_CREATE_BOOTCAMP',
    RES_CREATE_BOOTCAMP : 'RES_CREATE_BOOTCAMP',
    REQ_GET_BOOTCAMP_BY_ID : 'REQ_GET_BOOTCAMP_BY_ID',
    RES_GET_BOOTCAMP_BY_ID : 'RES_GET_BOOTCAMP_BY_ID',
    REQ_GET_DAFTAR_APPLY : 'REQ_GET_DAFTAR_APPLY',
    RES_GET_DAFTAR_APPLY : 'RES_GET_DAFTAR_APPLY',

    //ProgName
    REQ_GET_PROGNAME : 'REQ_GET_PROGNAME',
    RES_GET_PROGNAME : 'RES_GET_PROGNAME',

    //Trainer
    REQ_GET_TRAINER : 'REQ_GET_TRAINER',
    RES_GET_TRAINER : 'RES_GET_TRAINER',


    //Cancidat
    REQ_GET_CANDIDAT_APPLY : 'REQ_GET_CANDIDAT_APPLY',
    RES_GET_CANDIDAT_APPLY : 'RES_GET_CANDIDAT_APPLY',
    REQ_UPDATE_CANDIDAT_APPLY : 'REQ_UPDATE_CANDIDAT_APPLY',
    RES_UPDATE_CANDIDAT_APPLY : 'RES_UPDATE_CANDIDAT_APPLY',
    REQ_GET_CANDIDAT_FILTERING : 'REQ_GET_CANDIDAT_FILTERING',
    RES_GET_CANDIDAT_FILTERING : 'RES_GET_CANDIDAT_FILTERING',
    REQ_UPDATE_CANDIDAT_FILTERING : 'REQ_UPDATE_CANDIDAT_FILTERING',
    RES_UPDATE_CANDIDAT_FILTERING : 'RES_UPDATE_CANDIDAT_FILTERING',
    REQ_GET_CANDIDAT_CONTRACT : 'REQ_GET_CANDIDAT_CONTRACT',
    RES_GET_CANDIDAT_CONTRACT : 'RES_GET_CANDIDAT_CONTRACT',
    REQ_UPDATE_CANDIDAT_CONTRACT : 'REQ_UPDATE_CANDIDAT_CONTRACT',
    RES_UPDATE_CANDIDAT_CONTRACT : 'RES_UPDATE_CANDIDAT_CONTRACT',
    REQ_GET_CANDIDAT_DISQUALIFIED : 'REQ_GET_CANDIDAT_DISQUALIFIED',
    RES_GET_CANDIDAT_DISQUALIFIED : 'RES_GET_CANDIDAT_DISQUALIFIED',
    REQ_UPDATE_CANDIDAT_DISQUALIFIED : 'REQ_UPDATE_CANDIDAT_DISQUALIFIED',
    RES_UPDATE_CANDIDAT_DISQUALIFIED : 'RES_UPDATE_CANDIDAT_DISQUALIFIED',
    REQ_GET_CANDIDAT_NOTRESPONDING : 'REQ_GET_CANDIDAT_NOTRESPONDING',
    RES_GET_CANDIDAT_NOTRESPONDING : 'RES_GET_CANDIDAT_NOTRESPONDING',
    REQ_UPDATE_CANDIDAT_NOTRESPONDING : 'REQ_UPDATE_CANDIDAT_NOTRESPONDING',
    RES_UPDATE_CANDIDAT_NOTRESPONDING : 'RES_UPDATE_CANDIDAT_NOTRESPONDING',
}

export default ActionType