const UserProfileActionType = {
    GETBYNAMEOREMAIL: "GETBYNAMEOREMAIL",
    GETBYNAMEOREMAIL_RESPONSE: "GETBYNAMEOREMAIL_RESPONSE",

    UPDATEPROFILE: "UPDATEPROFILE",
    UPDATEPROFILE_RESPONSE: "UPDATEPROFILE_RESPONSE",
    CHANGEPASSWORD: "CHANGEPASSWORD",
    CHANGEPASSWORD_RESPONSE: "CHANGEPASSWORD_RESPONSE",

    ADDEMAIL: "ADDEMAIL",
    ADDEMAIL_RESPONSE: "ADDEMAIL_RESPONSE",
    EDITEMAIL: "EDITEMAIL",
    EDITEMAIL_RESPONSE: "EDITEMAIL_RESPONSE",
    DELETEEMAIL: "DELETEEMAIL",
    DELETEEMAIL_RESPONSE: "DELETEEMAIL_RESPONSE",

    ADDPHONE: "ADDPHONE",
    ADDPHONE_RESPONSE: "ADDPHONE_RESPONSE",
    EDITPHONE: "EDITPHONE",
    EDITPHONE_RESPONSE: "EDITPHONE_RESPONSE",
    DELETEPHONE: "DELETEPHONE",
    DELETEPHONE_RESPONSE: "DELETEPHONE_RESPONSE",

    ADDADDRESS: "ADDADDRESS",
    ADDADDRESS_RESPONSE: "ADDADDRESS_RESPONSE",
    EDITADDRESS: "EDITADDRESS",
    EDITADDRESS_RESPONSE: "EDITADDRESS_RESPONSE",
    DELETEADDRESS: "DELETEADDRESS",
    DELETEADDRESS_RESPONSE: "DELETEADDRESS_RESPONSE",

    ADDEDUCATION: "ADDEDUCATION",
    ADDEDUCATION_RESPONSE: "ADDEDUCATION_RESPONSE",
    EDITEDUCATION: "EDITEDUCATION",
    EDITEDUCATION_RESPONSE: "EDITEDUCATION_RESPONSE",
    DELETEEDUCATION: "DELETEEDUCATION",
    DELETEEDUCATION_RESPONSE: "DELETEEDUCATION_RESPONSE",

    ADDEXPERIENCE: "ADDEXPERIENCE",
    ADDEXPERIENCE_RESPONSE: "ADDEXPERIENCE_RESPONSE",
    EDITEXPERIENCE: "EDITEXPERIENCE",
    EDITEXPERIENCE_RESPONSE: "EDITEXPERIENCE_RESPONSE",
    DELETEEXPERIENCE: "DELETEEXPERIENCE",
    DELETEEXPERIENCE_RESPONSE: "DELETEEXPERIENCE_RESPONSE",

    ADDSKILL: "ADDSKILL",
    ADDSKILL_RESPONSE: "ADDSKILL_RESPONSE",
    DELETESKILL: "DELETESKILL",
    DELETESKILL_RESPONSE: "DELETESKILL_RESPONSE",

    ADDRESUME: "ADDRESUME",
    ADDRESUME_RESPONSE: "ADDRESUME_RESPONSE",
    DELETERESUME: "DELETERESUME",
    DELETERESUME_RESPONSE: "DELETERESUME_RESPONSE",

    APPLYJOB: "APPLYJOB",
    APPLYJOB_RESPONSE: "APPLYJOB_RESPONSE",
}

export default UserProfileActionType