const UserProfileActionType = {
    GETBYNAMEOREMAIL: "GETBYNAMEOREMAIL",
    GETBYNAMEOREMAIL_RESPONSE: "GETBYNAMEOREMAIL_RESPONSE",
    UPDATEPROFILE: "UPDATEPROFILE",
    UPDATEPROFILE_RESPONSE: "UPDATEPROFILE_RESPONSE",

    ADDEMAIL: "ADDEMAIL",
    ADDEMAIL_RESPONSE: "ADDEMAIL_RESPONSE",
    EDITEMAIL: "EDITEMAIL",
    EDITEMAIL_RESPONSE: "EDITEMAIL_RESPONSE",
    DELETEEMAIL: "DELETEEMAIL",
    DELETEEMAIL_RESPONSE: "DELETEEMAIL_RESPONSE",

    ADDPHONE: "ADDPHONE",
    ADDPHONE_RESPONSE: "ADDPHONE_RESPONSE",
    EDITPHONE: "EDITPHONE",
    EDITPHONE_RESPONSE: "EDITPHONE_RESPONSE",
    DELETEPHONE: "DELETEPHONE",
    DELETEPHONE_RESPONSE: "DELETEPHONE_RESPONSE"

}

export default UserProfileActionType