const UserProfileActionType = {
    GETBYNAMEOREMAIL: "GETBYNAMEOREMAIL",
    GETBYNAMEOREMAIL_RESPONSE: "GETBYNAMEOREMAIL_RESPONSE",
    UPDATEPROFILE: "UPDATEPROFILE",
    UPDATEPROFILE_RESPONSE: "UPDATEPROFILE_RESPONSE",
}

export default UserProfileActionType